### ISSUE TITLE
Endings: The End

### ISSUE THREAD

**Issue by Masa0201** [0x1f440/TranslateHotelSowls#2]
![20200124181931_1](https://user-images.githubusercontent.com/60313150/73134361-1376e180-4079-11ea-8933-b398c13e7403.jpg)

Priority: B
Current: 『それ』は家に帰りたがった。そして私はその頼みを聞いてくれた。/nそれは正しいことだっただろうか。
Revised:『それ』は家に帰りたがった。そして私はその頼みを聞いてやった。/nそれは正しいことだっただろうか。

![20200124181939_1](https://user-images.githubusercontent.com/60313150/73134382-3a351800-4079-11ea-93cc-0ec7ae969b9d.jpg)

Priority: C
Current:僕はこの宇宙の何ものも分からないから・・・
Revised:私にはこの宇宙のことは何も分からないから・・・

line feed code "/n"
Priority: A>B>C
A: It has a bad effect on game playing.
B: Players misunderstand what it says.
C: Players can understand what it says, but it may seem strange.

**Comment by 0x1f440** [comment]
👍
