### ISSUE TITLE
Endings: Re-human

### ISSUE THREAD

**Issue by Masa0201** [0x1f440/TranslateHotelSowls#3]
![20200124144416_1](https://user-images.githubusercontent.com/60313150/73134734-605cb700-407d-11ea-8fe1-39fa1873f818.jpg)
Priority: C
Current:たとえ大金を払って生きた私の石は失うことになったが・・・/nみんな自由を享受して新しい人生を幸せに生きているだろう。/nそれで私は十分だ。
Revised:大金を払って手に入れた石を失うことになったが・・・/nみんな自由を享受して新しい人生を幸せに生きているだろう。/nそれで私は十分だ。

![20200124144432_1](https://user-images.githubusercontent.com/60313150/73134756-97cb6380-407d-11ea-912e-f48439dc3531.jpg)
Priority: C
Current:ゲストさんこんにちは。/n元気？
Revised:お客さんこんにちは。/n元気？

![20200124144457_1](https://user-images.githubusercontent.com/60313150/73134769-c2b5b780-407d-11ea-97f2-fa7cb3510912.jpg)
Priority: C
Current:・・・まだ何人かはそれを恋しがったりもする。
Revised:・・・まだ何人かは『それ』を恋しがったりもする。

![20200124144517_1](https://user-images.githubusercontent.com/60313150/73134782-f7297380-407d-11ea-8eba-7a53d5e41e59.jpg)
Priority: C
Current:‐ホテル・ソウルズの（相変わらずの）フロントスタッフが。
Revised:‐ホテル・ソウルズの（相変わらずの）フロントスタッフより。

line feed code "/n"
Priority: A>B>C
A: It has a bad effect on game playing.
B: Players misunderstand what it says.
C: Players can understand what it says, but it may seem strange.

**Comment by 0x1f440** [comment]
Thank you!
