### ISSUE TITLE
Endings: Bad Hunch

### ISSUE THREAD

**Issue by Masa0201** [0x1f440/TranslateHotelSowls#4]
![20200124115126_1](https://user-images.githubusercontent.com/60313150/73134811-60a98200-407e-11ea-8d3a-cabde1e8617d.jpg)
Priority: B
Current:なんか知らないけど、このホテルにもう泊まりたくなくて/nもう出発することにした。/n私の肉感がこのホテルは妙におかしいと言っている。/n何か大きくて怖い秘密がある隠されているように・・・
Revised:なんだか知らないけど、このホテルに泊まりたくなくて/nもう出発することにした。/n私の直感がこのホテルは妙におかしいと言っている。/nそして、何か大きくて怖い秘密が隠されていると・・・

line feed code "/n"
Priority: A>B>C
A: It has a bad effect on game playing.
B: Players misunderstand what it says.
C: Players can understand what it says, but it may seem strange.

**Comment by 0x1f440** [comment]
Thanks! 💕
