### ISSUE TITLE
Endings: New Job

### ISSUE THREAD

**Issue by Masa0201** [0x1f440/TranslateHotelSowls#5]
![20200124163344_1](https://user-images.githubusercontent.com/60313150/73134836-b5e59380-407e-11ea-8ec5-bcd50fa22530.jpg)
Priority: C
Current:ホテルで5日目の夜を越すてしまった私は/nもはや以前の私ではなかった。/n精神が・・・くもっている・・・
Revised:ホテルで5日目の夜を越してしまった私は/nもはや以前の私ではなかった。/n精神が・・・くもっている・・・

line feed code "/n"
Priority: A>B>C
A: It has a bad effect on game playing.
B: Players misunderstand what it says.
C: Players can understand what it says, but it may seem strange.

**Comment by 0x1f440** [comment]
👍
