### ISSUE TITLE
Endlings: Know Yourself

### ISSUE THREAD

**Issue by Masa0201** [0x1f440/TranslateHotelSowls#6]
![20200124142950_1](https://user-images.githubusercontent.com/60313150/73134870-fcd38900-407e-11ea-91ba-ca2d117c1955.jpg)
Priority: C
Current:ただ人間なんかがその薬を飲んではいけなかった。
Revised:ただの人間なんかがその薬を飲んではいけなかった。

line feed code "/n"
Priority: A>B>C
A: It has a bad effect on game playing.
B: Players misunderstand what it says.
C: Players can understand what it says, but it may seem strange.

**Comment by Masa0201** [comment]
The correction has been completed: GameScript.xlsx

**Comment by 0x1f440** [comment]
👍
