### ISSUE TITLE
Endings: Nobal Prize

### ISSUE THREAD

**Issue by Masa0201** [0x1f440/TranslateHotelSowls#7]
![20200124133803_1](https://user-images.githubusercontent.com/60313150/73134893-40c68e00-407f-11ea-9a53-2f00b962fdcc.jpg)
Priority: C
Current:この数多いお金なら私はもう何でもできる。
Revised:これだけお金があれば、もう何でもできる！

line feed code "/n"
Priority: A>B>C
A: It has a bad effect on game playing.
B: Players misunderstand what it says.
C: Players can understand what it says, but it may seem strange.

**Comment by Masa0201** [comment]
The correction has been completed: GameScript.xlsx

**Comment by 0x1f440** [comment]
Thank you!
